Lab 21 Worksheet

Name:  

Create a 1 by 4 row vector R of random integers, and also a 4 by 1 column vector C of random integers. Use matrix multiplication to multiply them. Can you multiply R times C? C times R?

In [3]:
# 1

import numpy as np
from numpy import array
from numpy import arange

R = np.random.randint(1,10,(1,4))
C = np.random.randint(1,10,(4,1))
print(R)
print(C)
print()
print(R @ C)
print()
print(C @ R)


[[4 1 7 9]]
[[3]
 [9]
 [9]
 [3]]

[[111]]

[[12  3 21 27]
 [36  9 63 81]
 [36  9 63 81]
 [12  3 21 27]]


For two square matrices that have the same dimensions, you can use both array multiplication and matrix multiplication on them. Create two 3 x 3 matrices and demonstrate this.

In [7]:
# 2

A = np.random.randint(1,5,(3,3))
B = np.random.randint(1,5,(3,3))
print(A)
print()
print(B)
print()
print(A * B)
print()
print(A @ B)

[[2 2 1]
 [4 1 3]
 [2 3 4]]

[[1 1 1]
 [3 1 2]
 [2 1 4]]

[[ 2  2  1]
 [12  1  6]
 [ 4  3 16]]

[[10  5 10]
 [13  8 18]
 [19  9 24]]


Create a vector x which consists of 20 equally spaced points in the range from -pi to + pi. Create a y vector which is sin(x). Plot the points.

In [9]:
# 3

import matplotlib.pyplot as plt
from math import pi

x = np.linspace(-pi, pi, 20)
y = np.sin(x)
plt.plot(x,y)


Find two ways to create a 3 x 5 matrix of all integer 100's, without using **full**.

In [10]:
# 4

mymat = np.zeros((3,5), dtype=np.int16) + 100
print(mymat)
print()

mymat = np.ones((3,5), dtype=np.int16) * 100
print(mymat)
print()


[[100 100 100 100 100]
 [100 100 100 100 100]
 [100 100 100 100 100]]

[[100 100 100 100 100]
 [100 100 100 100 100]
 [100 100 100 100 100]]



Generate a vector of 20 random integers, each in the range from 50 to 100. Create a variable evens that stores the even numbers from the vector, and a variable odds that stores the odd numbers from the vector.

In [11]:
# 5

v = np.random.randint(50,101,20)
print(v)
print()

evens = v[v % 2 == 0]
print(evens)
print()
odds = v[v % 2 != 0]
print(odds)

[89 55 59 66 99 83 82 85 69 96 95 89 72 52 70 89 86 54 96 79]

[66 82 96 72 52 70 86 54 96]

[89 55 59 99 83 85 69 95 89 89 79]


Write a function that will receive as input a square matrix of numbers, and will return True if it is a diagonal matrix, or False if not. Assume that the matrix is square. Hint: investigate the **all** method for this.

In [12]:
# 6

def isdiagonal(inmat):
    """Returns true if the square matrix is a diagonal matrix, False if not"""
    mat = np.copy(inmat)
    dg = np.diag(mat)
    newmat = np.diag(dg)
    logmat = newmat == mat
    return logmat.all()

A = np.array([[1,0,0],[0,2,0],[0,0,3]])
print(A)
print(isdiagonal(A))



[[1 0 0]
 [0 2 0]
 [0 0 3]]
True


Write a function that will receive as input a square matrix of numbers, and will return True if it is symmetric, or False if not. Assume that the matrix is square.

In [16]:
# 7

def issymmetric(inmat):
    """Returns true if the square matrix is symmetric, False if not"""
    mat = np.copy(inmat)
    return (mat == mat.T).all()

A = np.array([[1,0,0],[0,2,0],[0,0,3]])
print(A)
print(issymmetric(A))

B = np.array([[1,2,3],[2,4,5],[3,4,6]])
print(B)
print(issymmetric(B))

[[1 0 0]
 [0 2 0]
 [0 0 3]]
True
[[1 2 3]
 [2 4 5]
 [3 4 6]]
False


And now for some real fun... write your own matrix multiplication function!  To make it easier, assume that the matrix dimensions are correct.  Go back and read the description in the Reading. For each element in C, you will have 2 nested loops to loop through the rows of A and columns of B.

In [20]:
# 8

def mymatmult(A, B):
    """ Performs matrix multiplication A * B."""
    rowsC = A.shape[0]
    colsC = B.shape[1]
    C = np.zeros((rowsC, colsC), dtype = np.int64)
    for i in range(rowsC):
        for j in range(colsC):
            C[i,j] = (A[i,:] * B[:,j]).sum()
    return C

A = np.array([[1,2,3],[4,5,6],[7,8,9]])
B = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(A)
print()
print(B)
print()
print(mymatmult(A,B))
print()
print(A @ B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]

[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]
