Lab 20 Worksheet.

Create two 1 by 5 arrays using arange. Use vstack to concatenate them into a 2D array.

In [ ]:
# 1
import numpy as np
from numpy import arange
arr1 = arange(2,7)
arr2 = arange(3,8)
mat = np.vstack((arr1, arr2))
print(mat)

[[2 3 4 5 6]
 [3 4 5 6 7]]


Create a 3D array of all zeros. Print it.

In [ ]:
# 2
arr3d = np.zeros((2,4,3))
print(arr3d)

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


Use the **ravel** method on your array of all zeros.

In [ ]:
# 3
print(arr3d.ravel())

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


Write an expression that will sum only the values in a vector variable “v” (1D variable) that are greater than or equal to 4.  Use logical indexing.

In [ ]:
# 4
v = np.array([1,5, -2, 11, 4])
print(v[v > 4])
print(sum(v[v> 4]))

[ 5 11]
16
16


Create a 3 by 5 array (matrix) of all random integers in the range from 50 to 100. Write code that will count how many elements are greater than 80.

In [ ]:
# 5
arr = np.random.randint(50, 100, (3,5))
print(arr)
print(arr[arr > 80].size)


[[78 66 84 71 74]
 [67 89 52 73 76]
 [61 81 85 74 76]]
4


Use **linspace** to create an array with 9 elements, from 1 to 5 in steps of 0.5.

In [ ]:
# 6
ls = np.linspace(1,5,9)
print(ls)

[1.  1.5 2.  2.5 3.  3.5 4.  4.5 5. ]


Create a 1D array (vector) with 10 linearly spaced points in the range from 1 to 19. Reshape this into a 2D array.

In [ ]:
# 7
arr1d = np.linspace(1,19,10)
arr2d = arr1d.reshape(2,5)
print(arr2d)

[[ 1.  3.  5.  7.  9.]
 [11. 13. 15. 17. 19.]]


Create a 2D array. Write nested for loops to print the array in a table format.

In [ ]:
# 8
arr2d = np.array([[33, 2, 11], [5, 4, 2]])
for row in arr2d:
    for col in row:
        print(f'{col:4d}', end=" ")
    print()

  33    2   11 
   5    4    2 


Create the 3x3 matrix [ 1 2 3 ; 4 5 6 ; 7 8 9 ] and then:
a) Transpose the matrix using a list comprehension
b) Transpose the matrix using a for loop

In [ ]:
# 9
# using a list comprehension
matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
transposed_matrix = [[row[i] for row in matrix] for i in range(len(matrix[0]))]
print(transposed_matrix)

# using a for loop
matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
transposed_matrix = []

for i in range(len(matrix[0])):
    transposed_row = []
    for row in matrix:
        transposed_row.append(row[i])
    transposed_matrix.append(transposed_row)

print(transposed_matrix)

[[1, 4, 7], [2, 5, 8], [3, 6, 9]]
[[1, 4, 7], [2, 5, 8], [3, 6, 9]]
